### ISSUE TITLE
Аттрибут :from

### ISSUE THREAD

**Issue by vsevolod** [nepalez/sms_aero#1]
Сейчас требуется аттрибут :from для отправки смс.

И отправка смс работает через вызов операции:
```ruby
@client.operations[:send_sms].call(
  text: text,
  to: to,
  type: type,
  from: configuration.from
)
```
При вызове метода - через метод миссинг в args приходит пустой массив:
```ruby
    48: def method_missing(name, *args)
 => 49:   require 'pry'; binding.pry
    50:   op = operations[name.to_sym]
    51:   op ? op.call(*args) : super
    52: end

2.3.3 (#<SmsAero:0x00000007284ab8>):0 > name
=> :send_sms
2.3.3 (#<SmsAero:0x00000007284ab8>):0 > args
=> []

```

**Comment by nepalez** [comment]
Ох, я кажется пропустил (ажно на 2 месяца) пропустил Ваш коммент.
Постараюсь на неделе посмотреть

**Comment by vsevolod** [comment]
Не могу сейчас это воспроизвести. Возможно как-то исправил. Сегодня вечером ещё посмотрю.

**Comment by nepalez** [comment]
Ага, спасибо! У меня этот гем работает в одном проекте, но он как-то там тихо работает, я к нему и не возвращался уж давно

**Comment by nepalez** [comment]
Закрываю за давностию. Да и в новой версии я переписал этот роут -- сейчас он работает одновременно с группами и имейлами
