### ISSUE TITLE
0.0.x branch request

### ISSUE THREAD

**Issue by Earendil95** [nepalez/sms_aero#3]
Hello!
Can you create branch for 0.0.x versions? In our project we have rails 4.1 and so we can't use evil-client 2.0, that depends on rack 2.0.
But we need one more feature from sms aero api - [HLR request](https://smsaero.ru/api/description/#hlr). I've add [this](https://github.com/Earendil95/sms_aero/tree/add-hlr) and want to open PR to your repo, but of course not to master.

**Comment by nepalez** [comment]
Hi!

I've created [this one](https://github.com/nepalez/sms_aero/tree/beta). Please, let me now whether it is what you need.

And yes, feel free to open a PR )
(not sure, whether I could look it through before weekend, though)

**Comment by Earendil95** [comment]
Yes, it what I'm need :)
Opened a [PR](https://github.com/nepalez/sms_aero/pull/4)
