### ISSUE TITLE
Is it wrong channel types?

### ISSUE THREAD

**Issue by jarosluv** [nepalez/sms_aero#6]
Hello, @nepalez, thanks for the gem!

I have a question. Why channel types in gems' `Channel` differ from [API v1 documentation](https://smsaero.ru/api/v1#send-sms)?
There are `1 2 3 4 6` instead of `4 5 6 7 8`.

If my thoughts are right, I prepared a PR https://github.com/nepalez/sms_aero/pull/7.

**Comment by nepalez** [comment]
@jarosluv Thanks!
It seems the docs were changed for the v1 since I first implemented it
I've merged the PR and updated a version
